pipeline {
  agent any
  environment {
    AWS_PUBLIC_IP_PROD = '18.204.62.90'
  }

  stages {
    stage('Deploy to Production') {
      steps {
        sh '''
          # remove the files
          ssh -i "/var/lib/jenkins/.ssh/aws-key-pair.pem" -o StrictHostKeyChecking=no ec2-user@${AWS_PUBLIC_IP_PROD} "sudo rm -rf /var/www/html/*"
          # copy the files to the prod server
          scp -i "/var/lib/jenkins/.ssh/aws-key-pair.pem" -o StrictHostKeyChecking=no -r ./* ec2-user@${AWS_PUBLIC_IP_PROD}:/var/www/html
          # restart the apache server
          ssh -i "/var/lib/jenkins/.ssh/aws-key-pair.pem" -o StrictHostKeyChecking=no ec2-user@${AWS_PUBLIC_IP_PROD} "sudo systemctl restart httpd"
        '''
      }
    }
  }
}